### ISSUE TITLE
Add support for C closures

### ISSUE THREAD

**Issue by swisspol** [cesanta/v7#534] opened 2015-12-05 21:46 UTC
It would be very nice to be able to provide a an arbitrary auxiliary pointer when creating a C function. This way the pointer could be used for closures e.g. C++11 lambdas, GCD, etc... while the C function pointer itself would remain constant.

**Comment by mmikulicic** [comment] 2015-12-05 23:15
The simplest solution for most use cases would be to leverage the `this` implicit argument and use bound functions:

This for that
----------------

```js
function foo() { return this }
foo_one = foo.bind("one");
foo_two = foo.bind("two");
foo_one(); // -> "one"
```

Doing that in C requires some more code because we don't expose a quick "bind" helper:

```c
v7_val_t Foo(struct v7 *v7) {
  v7_val_t me = v7_get_this(v7);
  if(!v7_is_foreign(me)) {
    printf("Foo not bound to a auxiliary pointer");
  } else {
    printf("Foo bound on %s\n", (const char*) v7_to_foreign(me));
  }
  return v7_create_undefined();
}

v7_val_t make_my_closure(v7_val_t func, void *data) {
  v7_val_t res, args = v7_create_array(v7);
  v7_array_push(v7, args, func);
  v7_array_push(v7, args, v7_create_foreign(v7, data));
  v7_exec_with(v7, "this[0].bind(this[1])", args, &res);
  return res;
}

void initExample(struct v7 *v7) {
  v7_val_t foo = v7_create_function(v7, Foo, 0);
  v7_set(v7, v7_global(v7), "foo", ~0, 0, foo);
  v7_set(v7, v7_global(v7), "foo_one", ~0, 0, make_my_closure(foo, "one"));
  v7_set(v7, v7_global(v7), "foo_two", ~0, 0, make_my_closure(foo, "two"));
}

```

This should work well for most of the cases unless you want your bound closure/lambda/C++ method/whatever to also behave like a JS method, and access the true JS `this` value 

In that case, read on.

Generalised bind
-----------------------

Closures and first order functions allow you do do many nice things, and since JS has both, why don't we use JS to implement C closures ?

```js
function makeFoo(fun, data) {
  var me = this;
  return function() {
     fun.call(me, data);
  }
}
```

```c
v7_val_t Foo(struct v7 *v7) {
  printf("Foo bound to %s\n", (const char*) v7_to_foreign(v7_arg(v7, 0)));
}

v7_val_t make_my_closure(v7_val_t func, void *data) {
  v7_val_t res, args;
  v7_own(v7, &func);
  args = v7_create_array(v7);
  v7_own(v7, &args);
  v7_array_push(v7, args, func);
  v7_array_push(v7, args, v7_create_foreign(v7, data));
  v7_exec_with(v7, "makeFoo(this[0], this[1])", args, &res); // <- we might definitely make this less clumsy
  v7_disown(v7, &args);
  v7_disown(v7, &func);
  return res;
}

void initExample(struct v7 *v7) {
  v7_val_t foo = v7_create_cfunction(v7, Foo);
  v7_own(v7, &foo);
  v7_set(v7, v7_global(v7), "foo_one", ~0, 0, make_my_closure(foo, "one"));
  v7_set(v7, v7_global(v7), "foo_two", ~0, 0, make_my_closure(foo, "two"));
  v7_disown(v7, &foo);
}
```

With enough JS-fu you can make a JS function that will add your "aux" data as first arg or last arg of any C function with an arbitrary arglist. Or call your C trampoline with two foreign pointers (C function and C aux data). Or you can do whatever else you want. The idea is that you can "generate" how many function "instances" you want in JS by just returning a JS closure.

BTW, that's exactly how `Function.prototype.bind` is implemented. This is the actual implementation in the V7 JS stdlib:

```js
    Object.defineProperty(Function.prototype, "bind", {
      writable:true,
      configurable: true,
      value: function(t) {
        var f = this;
        return function() {
          return f.apply(t, arguments);
        };
    }});)
```

Both this and the previous approach however might look unappealing for one reason: they both require some JS code to be executed in order to create such a binding. This might be unappealing because executing JS code:

1. consumes more memory and _now_ it might not be the right time to do it
2. might trigger the GC and _now_ is one of such _latency sensitive_ moments, you know
3. or the GC might be inhibited to simplify tracking of the GC rootset: C functions that trigger execution of JS code have to be prepared to deal with the GC scanning and possibly updating pointers.

We still haven't finally settled down a set of rules that makes it as easy as possible to write C functions that deal with the JS engine while making sure it makes sense on a severely memory constrained environment (like 10-20 Kb of free heap).

The bottom line is that being able to handle a common pattern such as a `(function,data)` in a more native way pair might be worth some thought:

A more direct approach
-------------------------------

    DISCLAIMER: This below is just for the sake of keeping thoughts well nourished.
    We might not go ahead and extend V7 to in this direction given that our first priority
    is to focus on the most common things and keep it as simple as possible
    (but not simpler than that) for the time being.

Our low level C function is a value that has enough room to just fit a C function pointer.

However, a callable JS object wrapper can be put around such a cfunction value and used to hold arbitrary properties.

As mentioned in #524, this topic would clearly benefit of some documentation.

---

Now, the problem is: once your C function gets called we currently don't give the C function the ability to access the object through which it was called.

In JS that would be:

```
function foo() {
  arguments.callee;
}
```

We don't expose the `arguments` array object to the C function but instead provide arg accessor function. This is done in order to leave us the freedom to not actually use an array object underneath and to not go at great lengths at emulating array like access to using a fake `arguments` object for C code.

---

We could add a `v7_val_t v7_callee(v7)` function to the public API. Example use:

```c
v7_val_t Foo(struct v7 *v7) {
  v7_val_t f = v7_callee(v7);
  v7_val_t d = v7_get(v7, f, "data", ~0);

  // then you do something with your user data, e.g.
  printf("Foo bound to %s\n", (const char*) v7_to_foreign(d));
}

v7_val_t make_my_closure(v7_val_t func, void *data) {
  v7_val_t fo = v7_create_object(v7);
  v7_set_proto(v7, fo, v7_get(v7, v7_get(v7, v7_global(v7), "Function", ~0), "prototype", ~0)); // <- clumsy
  v7_set(v7, fo, "", V7_PROPERTY_HIDDEN, func); // <- magic
  v7_set(v7, fo, "data", ~0, 0, v7_create_foreign(data));
  return fo;
}

void initExample(struct v7 *v7) {
  v7_val_t foo = v7_create_cfunction(v7, Foo);
  v7_set(v7, v7_global(v7), "foo_one", ~0, 0, make_my_closure(foo, "one"));
  v7_set(v7, v7_global(v7), "foo_two", ~0, 0, make_my_closure(foo, "two"));
}
```

Assuming that the clumsy and magic parts are addressed, that approach would have the advantage of allowing an arbitrary number of auxiliary data to be attached to the C function _and_ somewhat fit in the JS language.

NOTE: the usage of `arguments.callee` has been disallowed in strict mode. However the rationale for doing so doesn't apply here.

**Comment by swisspol** [comment] 2015-12-05 23:17
Did you just write all this? :open_mouth:

**Comment by mmikulicic** [comment] 2015-12-05 23:25
sorry quite long :-) but there are a few options and some tradeoffs.

btw, thanks for your many very useful comments in our issue tracker!

**Comment by swisspol** [comment] 2015-12-05 23:34
Oh no, I'm just super impressed by your suggestion to my comment :smile: 

I'm also quite impressed by v7 so far!

**Comment by swisspol** [comment] 2015-12-05 23:45
FWIW Lua has built-in support for C closure which is convenient.

**Comment by swisspol** [comment] 2015-12-06 02:12
Some thoughts on what you wrote:
- I got C++ lambdas to work with your first approach, so thanks much for that!
- I like the generalized bind idea: it's elegant because it's pushing the closure burden to JS which already supports that, and I'm not so much concerned about performance (I'm doing desktop/mobile apps, not embedded systems).
- I like the `v7_callee()` idea as well: it's intriguing but still clean, quite flexible, and that would not trigger GC right?

**Comment by mmikulicic** [comment] 2015-12-06 08:13
Yeah the callee approach would allow to create several C function objects
from C code that share the same underlying cfunction pointer value and have
different data properties.

The runtime cost would be only the allocation of the objects and data
properties and so it's compatible with the simplified runtime model
currently enjoyed by C functions: the GC is inhibited until control reaches
back to the evaluator.

**Comment by mmikulicic** [comment] 2015-12-09 15:47
Closing because there already exists way to solving the task described in the subject

**Closed by mmikulicic** 2015-12-09 15:47 UTC
Labels: feature
